# Generated by Django 5.2 on 2025-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(max_length=50)),
                ('battery_capacity', models.FloatField()),
                ('battery_type', models.CharField(max_length=100)),
                ('range_km', models.FloatField()),
                ('motor_type', models.CharField(max_length=50)),
                ('motor_power', models.FloatField()),
                ('charging_type', models.CharField(max_length=30)),
                ('max_charging_rate', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField()),
                ('battery_health', models.FloatField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('software_version', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
